import type { Metadata } from "next";
import "./globals.css"; // グローバルCSSをインポート

export const metadata: Metadata = {
  title: "My Next App", // アプリケーションのデフォルトタイトル
  description: "Generated by create next app", // デフォルトの説明
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja"> {/* 日本語設定 */}
      <body>
        {/* ここにヘッダーやナビゲーションなどの共通コンポーネントを追加できます */}
        <main>
          {children} {/* 各ページのコンテンツがここに表示されます */}
        </main>
        {/* ここにフッターなどの共通コンポーネントを追加できます */}
      </body>
    </html>
  );
}
